from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
import time

email = input('The email adress to be created: ')
passw = input('The password to be created: ')
driver_path = "C:\\Users\\XXXX\\Desktop\\checker\\chromedriver.exe"
options = Options()
options.add_argument('--headless')
options.add_argument('--disable-gpu')
browser = webdriver.Chrome(executable_path=driver_path)
browser.get('https://www.kirmizikedi.com/uyelik/yeni-uyelik')
time.sleep(5)
name = browser.find_element_by_name('Member.FirstName')
name.send_keys('Metin')
surname = browser.find_element_by_name('Member.LastName')
surname.send_keys('Şen')
mail = browser.find_element_by_name('Member.EmailAddress')
mail.send_keys(email)
mmail2 = browser.find_element_by_name('Member.EmailAddressConfirmation')
mmail2.send_keys(email)
password = browser.find_element_by_name('Member.Password')
password.send_keys(passw)
password2 = browser.find_element_by_name('Member.PasswordConfirmation')
password2.send_keys(passw)
time.sleep(3)
Sözlesme = browser.find_element_by_xpath('/html/body/section[2]/div/div[2]/div/form/div[5]/div/input')
Sözlesme.click()
time.sleep(1)
Sözlesme.send_keys(Keys.RETURN)
time.sleep(5)
try:
    wrong = browser.find_element_by_xpath('/html/body/section[2]/div/div[1]/div/div').text
    print(wrong)
except:
    pass
dosya = open('account.txt','a', encoding='utf-8')
dosya.write('Account: '+email+':'+passw+'\n')
print('Account created.')
browser.get('https://www.kirmizikedi.com/uyelik/uye-giris')
giris = browser.find_element_by_id('EmailAddress')
giris.send_keys(email)
parola = browser.find_element_by_id('Password')
parola.send_keys(passw)
click_login = browser.find_element_by_xpath('/html/body/section[2]/div/div[1]/div/form/button')
click_login.click()
time.sleep(1)
browser.get('https://www.kirmizikedi.com/uye/adreslerim')
adres = browser.find_element_by_xpath('/html/body/section[2]/div/div[1]/div[1]/a')
adres.click()
adres_name = browser.find_element_by_name('Address.Name')
adres_name.send_keys('ev')
person = browser.find_element_by_name('Address.DeliveryPerson')
person.send_keys('metin sen')
ülke = Select(browser.find_element_by_name('Address.CountryId'))
ülke.select_by_value('1')
time.sleep(1)
sehir = Select(browser.find_element_by_name('Address.CityId'))
sehir.select_by_value('4')
time.sleep(1)
TownID = Select(browser.find_element_by_name('Address.TownId'))
TownID.select_by_value('52')
Postal_code = browser.find_element_by_name('Address.PostalCode')
Postal_code.send_keys('21100')
Street_adress = browser.find_element_by_name('Address.StreetAddress')
Street_adress.send_keys('asdasdas56d1asd1as65d1as')
phone = browser.find_element_by_name('Address.PhoneNumber')
phone.send_keys('5513694951')
Default = browser.find_element_by_name('Address.IsDefault')
Default.click()
Save = browser.find_element_by_xpath('/html/body/section[2]/div/div[1]/div[1]/div[3]/form/button')
Save.click()
print('The account has been made, the things that needed to be done were done, you can use the checker now.')
time.sleep(5)
browser.quit()

